### ISSUE TITLE
Discuss options to remove depenency Jango simple history

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1091]
look at dependency on Jango simple history and impact is has on future deveiopments

**Comment by JackScanlon** [comment]
# Points of discussion

### Flexibility
1. We have had several issues relating to migration of data due to the difficulty of overriding _Django-Simple-History_ (DSH) behaviour - for example, maintaining historical IDs have been particularly difficult
2. Automatic migration of DSH can result in loss of data and/or fields if the parent model is changed. It is possible to add extra fields through Receivers/Signals but we lose readability. Indexing has been a big pain point because you are unable to maintaing indexes without custom SQL migrations when the ORM would have handled this just fine
3. Vendor lock in - difficult to migrate away from using this dependency if our requirements change and/or it is no longer supported by the project owners
4. The `history_id` is a auto incrementing PK field which results in version IDs that appear to be nonsensical to the user e.g. updating PH1 would result in a version ID greater than 10,000 (since we have more than 10,000 historical rows). This could be managed using atomicity and incrementing the version ID for that particular phenotype e.g., updating a phenotype would result in version + 1, so updating a phenotype with a version ID of 1 would result in PH1/2 instead of PH1/10000

### Performance costs
1. DSH automatically adds a `db_index` to each field which ↑memory
2. We have to run concurrent indexes on partitioned tables to ↑performance, which results in a ↑memory
3. Requires multiple joins to get a meaningful read which ↑query complexity and ↓performance

### Current implementation
1. **Phenotypes**

To get a meaningful first read of a Phenotype we have to first read the phenotype table, join that with its historical table (ordered by historical date and/or id), and then finally reverse join through the published table.

Without DSH, we could use a single table that defines a `history_id` field and a `status` field to describe whether that version of a phenotype is a draft, published, or any other state. Avoiding unnecessary partioning will ↑performance and ↓complexity.

The aforementioned implementation would also avoid having to index both the current & historical tables, which ↑memory.

2. **Concepts**

To get a meaningful first read of a Concept we have to first read the concept table:
  - Lookup the Concept table, join with its PublishedConcept table if we are examining a published entity
  - Join with its historical table
  - Find any HistoricalComponent that has the same `history_date` and `concept_id` of the HistoricalConcept, then join across each of its historical entries to ensure it's never been deleted
  - Find a HistoricalCodelist by its `component_id` and `history_date` that relates to this Component, excluding any deleted rows
  - Find any HistoricalCode by its `codelist_id` and `history_date` that relates to this CodeList, excluding any deleted then join across each of its historical entries to ensure it's never been deleted

As you can see, we have several items to join but we are unable to use ManyToMany and OneToOne fields because DSH doesn't support it without implementing Receivers/Signals. Similarly, due to the reliance on DSH across each of the tables and how we join, we have to duplicate the data on every change of the Concept and its children.

This implementation was required due to the initial requirements of the system, i.e.: concepts can be published, codes could be uploaded without validation. 

However, this is no longer required due to the integration of Concepts within Phenotypes and our intention to validate Codes in the future, so we are ↑memory, ↓performance and ↑query complexity without much benefit.

Concepts and child Rulesets could be managed through M2M through fields and subsequent M2M fields to the associated codes which would ↑performance, ↓memory and ↓query complexity.

**Comment by JackScanlon** [comment]
# Impact
Relates to & impacts on:
- #1097
- #1096
