### ISSUE TITLE
How to populate metadata in a concept using yaml file?

### ISSUE THREAD

**Issue by JamesAFarrell** [SwanseaUniversityMedical/concept-library#1399]
Hi,

How can metadata (e.g. publications, doi ect.) be populated in a concept using the .yaml file?

For [this concept](https://conceptlibrary.saildatabank.com/concepts/C3389/version/10434/detail/) I have populated these fields in the .yaml file attached (.txt as github doesn't upload .yaml) but they are not registering.

Thanks

[yaml_as_txt.txt](https://github.com/SwanseaUniversityMedical/concept-library/files/12683313/yaml_as_txt.txt)

**Comment by ieuans** [comment]
Hi James,

Sorry for the delay in getting back to you. 

You may be aware that we're making some big changes to the ConceptLibrary/PhenotypeLibrary that should be live by the end of the week - this includes a user interface for creating/editing phenotypes on the site rather than through the API/packages.

In the new site, concepts take a backseat role - the phenotypes will contain all of the information (and more) that the concepts used to hold. For now, I would recommend populating the phenotype with the publications rather than the concepts. 

If you do still want to populate these fields for the concept, you can do it manually through calling the api_concept_create/ or api_concept_update/ endpoints - please let me know if you need any help with this and I can forward a script to do this for you.

**Comment by ieuans** [comment]
Hi James, 

Just to let you know that we've pushed our most recent changes to the production site (https://conceptlibrary.saildatabank.com/), changes include:
- It's now possible to create phenotypes using an interface on the website itself (https://conceptlibrary.saildatabank.com/create/), documentation here: https://conceptlibrary.saildatabank.com/documentation/clinical-coded-phenotype-docs
- You can now view all phenotypes you have created/have access to via your group permissions through the 'my collections' page (https://conceptlibrary.saildatabank.com/profile/collection/). In addition to this, you can also archive and restore phenotypes that have never been published
- Several other improvements to the site

With the changes to the production site, we've also made major changes to the API and the client packages:
- Released a Python version of the package (https://github.com/SwanseaUniversityMedical/pyconceptlibraryclient)
- Re-implemented the R package in a class-based structure, with some changes to how the package is used. The README covers every function that's now available: https://github.com/SwanseaUniversityMedical/ConceptLibraryClient

**Comment by JamesAFarrell** [comment]
Hi Ieuan,
Thanks very much for the information provided here (and over email). I'll close this issue now.
Best wishes!
