### ISSUE TITLE
Discuss permission model implementation

### ISSUE THREAD

**Issue by ieuans** [SwanseaUniversityMedical/concept-library#1468]
As discussed in this thread: https://hiru.slack.com/archives/G010QHX24MN/p1699619145162889?thread_ts=1699534040.160599&cid=G010QHX24MN

### Dependencies
Folowing issues are dependent on the outcome of the permissions model
#1368 
#1449 
#1390

**Comment by DSThayer** [comment]
We had a meeting. Achieved. @elmessary has agreed to take the next step of proposing a model that we can further discuss and agree on.

Discussion points:

- Finer controls on sharing with colleagues within group
- Can phenotypes be part of more than one group? 
- Sharing with external person (share via link--temporary?)
- Clinical review workflow
- Sharing pre-publication for review
- Questions around ownership/permission levels. Single owner was problematic. Enabling all editors to take any actions is not necessarily ideal either.
- who can control the permissions section?
- who can publish/delete?
- Control over tags or collections--e.g. only ADP should own the ability to put the ADP collection on content. 
- Some permissions settings should possibly be at a higher level (group) rather than in each phenotype.
- Possible levels: admin, editor, collaborator.
- Groups doing their own approval for publication. 
- What if there are different brands? Approval process? 
- When can you reference other content that is not published?
