### ISSUE TITLE
Statistics and Analytics - Discussion / Design on tracking usage

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1498]
need to decide how best to track the actual usage of the Library eg number of downloads , API connections

**Comment by ieuans** [comment]
R.E.

1. Who is the consumer? Will be sharing all or a part of this with an external group? Are they technical or non-technical? Will we publish phenotype-specific figures on the detail/ page?
2. Dependent on consumer, do we need visualisations?
3. What are the metrics? e.g.
 - API confirmed, but will we be monitoring hits per page/phenotype on the website?
 - Will we be tracking usage of certain features on the website, e.g. downloading a codelist, requests for publication, creating/updating phenotypes?
 - Are we tracking referrals between phenotypes?
4. Are we tracking this per brand? e.g. to be able to provide brand-specific analytics to ADP / HDRUK? How do we fit this in with the permission model? Who has access?
5. How do we want to track 'hits' or 'downloads'? Are we recording IP (will require changes to our privacy policy)? If so, how often do we count a single IP as a unique hit?
6. What about location based data?

Future concerns:
1. Considerations around our implementation so that it's extensible by our statistics system in the future, e.g. tracking disease categories
2. Should we track data based on user reported information, e.g. group, institution, location (After UAM)
