### ISSUE TITLE
Blog page: Review current block packages available

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1673]
Review blog packages currently available and write up a list of pros and cons for each.  Does 1 stand out more than others?

What features come with blog tool and see if we can use them.

**Comment by nayim7868** [comment]
BRIEF Summary of Blog Packages for the Concept Library Website

Django CMS with Django CMS Blog
Pros:
Works well with existing Django projects, using familiar Django setup.
Allows adding features with plugins and placeholders.
Uses the same admin panel as Django, making it easier to manage.
Built-in support for different languages.
Active community with strong support and frequent updates.
Includes version control, publishing workflows, drag-and-drop interface for arranging content, tags, categories, and comments.
Cons:
Initial setup can be tricky but is well-documented.
Slight performance impact due to its modular nature, but manageable.

Wagtail
Pros:
User-friendly and modern admin panel.
Exclusive StreamField Feature allows for creating dynamic and complex content.
Convenient tools for handling images and documents.
Large and popular with active communities including lots of documentation.
Version control which allows to save past and future versions
Includes form builders, SEO tools, and integration with third-party services like Elasticsearch.
Cons:
Requires learning Wagtail-specific models and page setup.
Different from Django’s admin, which might complicate management.

Mezzanine
Pros:
Includes blogging, page management, and SEO tools.
Easier to set up compared to Wagtail.
Intuitive for non-technical users.
Cons:
Not as flexible as Wagtail and Django CMS.
Can be heavier on performance due to many features.

Zinnia
Pros:
Includes comments, tags, categories, and feeds.
Built-in support for SEO best practices.
Comprehensive guides and examples.
Cons:
Not as actively maintained as Wagtail or Django CMS.
Customising the blog can be complex.

Puput (Built on Wagtail)
Pros:
Inherits powerful features of Wagtail.
Designed specifically for blogging with tags, categories, and comments.
Benefits from Wagtail’s user-friendly design.
Cons:
Requires setting up and understanding Wagtail.
Smaller community compared to Wagtail alone.

Which Ones Stand Out?
Django CMS with Django CMS Blog
Why it stands out:
Fits well with existing Django projects, using familiar settings.
Supports plugins and placeholders for easy customization.
Uses Django's admin panel, making it simpler to manage everything in one place.

Wagtail
Why it stands out:
Offers a very user-friendly and modern admin panel.
StreamField allows for creating varied and dynamic content.
Excellent tools for managing images and documents.
Lots of support and documentation to help you learn quickly.

For the Concept Library project, Django CMS with Django CMS Blog can be ideal  as it integrates easily with existing Django projects, uses the same admin interface, and has strong community support. It fits well with the existing setup and makes it easy to manage everything in one place. It also includes version control, tags, categories, comments, and drag-and-drop content arrangement.
However, Wagtail is also a strong option. It offers a modern, user-friendly interface that makes content management enjoyable. Wagtails flexibility in creating dynamic content with StreamField feature and its excellent tools for handling media make it very convenient if the focus is on creating a modern and highly flexible content management system. It also has an active large community and documentation.
