### ISSUE TITLE
Potential bug: codelist CSV export function does not include bespoke groups (whereas JSON export does)

### ISSUE THREAD

**Issue by spiros** [SwanseaUniversityMedical/concept-library#983]
Reported by Mehrdad Mizani from BHF Data Science Centre.

The export function in JSON includes the bespoke groups in a codelist e.g. `"code_attributes":{"CALIBER.Category":"Acute MI not further specified"},` while CSV export does not.

**Comment by elmessary** [comment]
Now, code attributes are added to the csv output:
- If the phenotype contains one concept, each code attribute will be exported in a separate column in the csv.
- If the phenotype contains more than one concept, all the code attribute will be exported in one column called 'code_attributes' as a dictionary, this is because different concepts can have different attributes.
