### ISSUE TITLE
Tidy up Breathe phenotypes correct any issues

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#993]

**Comment by JackScanlon** [comment]
Issues with cases such as [PH785](https://conceptlibrary.saildatabank.com/HDRUK/phenotypes/PH785/version/2209/detail/)

# Plan
1. [ ] Assess data sources and publications, e.g. in the case of PH785, repositories were parsed as publications
2. [ ] Assess definition section e.g. as in the link above, "validated.No" was parsed as a link instead of two sentences.
3. [ ] Assess interpreted structure of scraped data, e.g. in the case of the aforementioned phenotype, code repositories may have be moved elsewhere and information unrelated to publications were listed as a publication

**Comment by JackScanlon** [comment]
Relevant Phenotype IDs are:

```
PH782, PH783, PH784, PH785, PH786, PH787, PH788, PH789, PH790, PH791, PH792, PH793, PH794, PH795, PH796, PH797, PH798, PH799, PH800, PH801, PH802, PH803, PH804, PH805, PH806, PH807, PH808, PH809, PH810, PH811, PH812, PH813, PH814, PH815, PH817, PH818, PH819
```

**Comment by JackScanlon** [comment]
Analysis has been performed and the results have been sent to @ZinnurovArtur
